## K-fold cross-validation 
- is a technique used to assess the performance and generalization ability of a machine learning model. 
- it helps to estimate how well the model will perform on unseen data by dividing the available dataset into K equally sized subsets or 'folds'. 
- the process involves training and evaluate the model K times, each time using a different fold as the validation set and the remaining folds as the training set 


In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

import numpy as np 
import matplotlib.pyplot as plt 


In [4]:
digits = load_digits()

#### Logistic Regression

In [5]:
X = digits.data
y = digits.target

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [8]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9527777777777777

## SVM 

In [9]:
from sklearn.svm import SVC
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4777777777777778

## Random forest

In [10]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975

## KFold cross validation 

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)


In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [17]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [18]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [19]:
scores_rf

[0.9315525876460768, 0.9432387312186978, 0.9098497495826378]

### cross_val_score function


In [20]:
from sklearn.model_selection import cross_val_score


In [23]:
# logistics 
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [24]:
# svm

cross_val_score(SVC(), digits.data, digits.target, cv=3
               )

array([0.96494157, 0.97996661, 0.96494157])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)


array([0.92988314, 0.95826377, 0.90984975])